// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqP0o_5FpUcMeqeLNQE783olc6aMdF-uQ',
    appId: '1:195127061456:web:732052ab6dbb88226827d5',
    messagingSenderId: '195127061456',
    projectId: 'library-bc474',
    authDomain: 'library-bc474.firebaseapp.com',
    storageBucket: 'library-bc474.firebasestorage.app',
    measurementId: 'G-EM3RLFCQC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp9AK6CndHlKcJjbm4YcOXAny-b-EVFU8',
    appId: '1:195127061456:android:d3688cc8dfd2566e6827d5',
    messagingSenderId: '195127061456',
    projectId: 'library-bc474',
    storageBucket: 'library-bc474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMFN6AkaWb7cvmxNZwoBN_6_kOFQk6aaU',
    appId: '1:195127061456:ios:1dc5ee752c4f60e56827d5',
    messagingSenderId: '195127061456',
    projectId: 'library-bc474',
    storageBucket: 'library-bc474.firebasestorage.app',
    iosClientId: '195127061456-kv686aj6cphhskdi15vuk6hlbbev1mh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMFN6AkaWb7cvmxNZwoBN_6_kOFQk6aaU',
    appId: '1:195127061456:ios:1dc5ee752c4f60e56827d5',
    messagingSenderId: '195127061456',
    projectId: 'library-bc474',
    storageBucket: 'library-bc474.firebasestorage.app',
    iosClientId: '195127061456-kv686aj6cphhskdi15vuk6hlbbev1mh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqP0o_5FpUcMeqeLNQE783olc6aMdF-uQ',
    appId: '1:195127061456:web:93f3d8098be367cc6827d5',
    messagingSenderId: '195127061456',
    projectId: 'library-bc474',
    authDomain: 'library-bc474.firebaseapp.com',
    storageBucket: 'library-bc474.firebasestorage.app',
    measurementId: 'G-Q9MPF4GTMJ',
  );
}
